### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by ahmetcetin**
Added doc directory to gitignore, adding docs folder, which is generated, in each release or merge, makes really difficult to track the changes, and makes the size of git unnecessarily big. If you use github to publish live version/documentation, maybe it's better to create separate repo for that purpose. Since last week, team feature is free in github, you can create a team called "React-Design-Editor" then move this repo there as main repo and add additional repo for preview site. I can help you if you want to set it up.

Btw, it's really very nice code, great job. Thanks a lot for sharing.

### CODE REVIEW

**Comment by salgum1114** [comment]
@ahmetcetin 

Thanks for the advice.

But, I think it is better to use the `gh-pages` branch rather than moving the repository.

**Comment by ahmetcetin** [comment]
yes, this might be easier indeed.

**Comment by salgum1114** [comment]
moved gh-pages branch!

**Comment by ahmetcetin** [comment]
Great, thx a lot!!!

**Pull request closed without merging**
